spring:
  redis:
    host: 47.98.197.239
    port: 6379
    database: 6
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
