
mongodb:
  master:
#    uri: mongodb://127.0.0.1:27017/sbac_master
    host: 127.0.0.1
    port: 27017
#    username: sbac
#    password: sbac
    database: sbac_master
  log:
#    uri: mongodb://127.0.0.1:27017/sbac_log
    host: 127.0.0.1
    port: 27017
#    username: sbac
#    password: sbac
    database: sbac_log



